## config
server.port: 8888
spring.application.name: configServer

## log
logging.level.org.springframework: info

## git repo
spring.cloud.config.server.git.uri: https://git.coding.net/liuzhudong/config-repo.git
spring.cloud.config.server.git.basedir: config-repo
spring.cloud.config.server.git.searchPaths: spring-cloud-config
spring.cloud.config.server.git.username: liuzhudong
spring.cloud.config.server.git.password: liu785827

##
management.security.enabled: false


